# Common Labels
labels:
  app: "kibana8-v1"
namespace: es-cluster-v8

# Ingress Configs
ingress:
  enabled: true
  context: "kibana8"
#  additionalAnnotations: |
#    nginx.ingress.kubernetes.io/auth-signin:  https://$host/oauth2/start?rd=$escaped_request_uri
#    nginx.ingress.kubernetes.io/auth-url:     https://$host/oauth2/auth

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "docker.elastic.co/kibana/kibana"
  tag: 8.11.1
replicas: "1"
httpPort: 5601
elasticsearchHosts: "http://esearch8-data.es-cluster-v8:9200"
serverBasePath: "/kibana8"
healthCheckPath: "kibana8/app/kibana"
healthChecks:
  enabled: true
  livenessProbePath: "/kibana8/"
  readinessProbePath: "/kibana8/"

# Additional Container Envs
env: |
  - name: ELASTICSEARCH_URL
    value: {{ .Values.elasticsearchHosts | quote }}
  - name: SERVER_BASEPATH
    value: {{ .Values.serverBasePath | quote }}
  - name: SERVER_REWRITEBASEPATH
    value: "true"