# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: environments/moz-health-dev\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:680148267093:key/ec32f7c0-a68c-4a8c-a35c-2ae00c0e93d2'