# Common Labels
labels:
  app: "hcm-moz-impl"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "hcm-moz-impl"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "moz_health_schema"
    image:
      repository: "moz-health-db"

# Container Configs
image:
  repository: "hcm-moz-impl"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/hcm-moz-impl/health"
  readinessProbePath: "/hcm-moz-impl/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/hcm-moz-impl-persister.yml"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: hcm-moz-impl
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: DHIS2_RECORD_KAFKA_CREATE_TOPIC
    value: create-dhis2-record
  - name: DHIS2_RECORD_KAFKA_UPDATE_TOPIC
    value: update-dhis2-record
  - name: DHIS2_DIGIT_MAPPING_KAFKA_CREATE_TOPIC
    value: create-dhis2-digit-mapping
  - name: DHIS2_DIGIT_MAPPING_KAFKA_UPDATE_TOPIC
    value: update-dhis2-digit-mapping
  - name: BOUNDARY_DATA_KAFKA_CREATE_TOPIC
    value: create-boundary-data
  - name: DHIS2_RECORD_DEFAULT_OFFSET
    value: "0"
  - name: DHIS2_RECORD_DEFAULT_LIMIT
    value: "10"
  - name: DHIS2_RECORD_SEARCH_MAX_LIMIT
    value: "50"
  - name: DHIS2_JOB_KAFKA_CREATE_TOPIC
    value: create-dhis2-job
  - name: DHIS2_JOB_KAFKA_UPDATE_TOPIC
    value: update-dhis2-job
  - name: DHIS2_JOB_DEFAULT_OFFSET
    value: "0"
  - name: DHIS2_JOB_DEFAULT_LIMIT
    value: "10"
  - name: DHIS2_JOB_SEARCH_MAX_LIMIT
    value: "50"
  - name: EGOV_DHIS2_HOST_URL
    value: "http://15.206.208.120:8080"
  - name: EGOV_DHIS2_HOST_AUTH_KEY
    value: ZUdvdjpUZW1wQDQ5NA==
  - name: EGOV_DHIS2_HOST_USERNAME
    value: admin
  - name: EGOV_DHIS2_HOST_PASSWORD
    value: district
  - name: EGOV_DHIS2_PAGE_SIZE
    value: "100"
  - name: EGOV_DHIS2_USERS_ENDPOINT
    value: /api/users
  - name: EGOV_DHIS2_USERS_FIELDS
    value: id,name,displayName,surname,firstName,userCredentials,organisationUnits
  - name: EGOV_DHIS2_ROLES_ENDPOINT
    value: /api/userRoles
  - name: EGOV_DHIS2_ROLES_FIELDS
    value: :all
  - name: EGOV_DHIS2_PROGRAMS_ENDPOINT
    value: /api/programs
  - name: EGOV_DHIS2_EVENTS_ENDPOINT
    value: /api/events
  - name: EGOV_DHIS2_ORGANISATION_UNIT_ENDPOINT
    value: /api/organisationUnits
  - name: EGOV_DHIS2_ORGANISATION_UNIT_FIELDS
    value: id,name,parent,path,level,children
  - name: EGOV_DHIS2_ORGANISATION_UNIT_LEVEL_ENDPOINT
    value: /api/organisationUnitLevels
  - name: EGOV_DHIS2_ORGANISATION_UNIT_LEVEL_FIELDS
    value: id,name,level
  - name: THREAD_CORE_POOL_SIZE
    value: "50"
  - name: THREAD_MAX_POOL_SIZE
    value: "100"
  - name: EGOV_DIGIT_HOST_AUTH_KEY
    value: ZWdvdi11c2VyLWNsaWVudDo=
  - name: EGOV_DIGIT_HOST_USERNAME
    value: khushali
  - name: EGOV_DIGIT_HOST_PASSWORD
    value: eGov@4321
  - name: EGOV_DIGIT_HOST_URL
    valueFrom:
        configMapKeyRef:
          name: egov-config
          key: egov-services-fqdn-name
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_DHIS2_ORGANISATION_UNIT_PROVINCES
    value: "SOFALA,TETE"
  - name: EGOV_PROJECT_TYPE_ID
    value: dbd45c31-de9e-4e62-a9b6-abb818928fd1
  - name: EGOV_PROJECT_TYPE
    value: LLIN-Default
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_FACILITY_SEARCH_PATH
    value: /facility/v1/_search
  - name: EGOV_FACILITY_CREATE_PATH
    value: /facility/v1/bulk/_create
  - name: EGOV_FACILITY_UPDATE_PATH
    value: /facility/v1/bulk/_update
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project
  - name: EGOV_PROJECT_SEARCH_PATH
    value: /project/v1/_search
  - name: EGOV_PROJECT_CREATE_PATH
    value: /project/v1/_create
  - name: EGOV_PROJECT_UPDATE_PATH
    value: /project/v1/_update
  - name: EGOV_BOUNDARY_NAME
    value: MOZAMBIQUE
  - name: EGOV_BOUNDARY_CODE
    value: LC00001
  - name: EGOV_MDMS_CREATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-create
  - name: EGOV_MDMS_CREATE_UPDATE_ENDPOINT
    value: /egov-mdms-create/v1/_update
  - name: EGOV_BOUNDARY_MASTER_NAME
    value: TenantBoundary
  - name: EGOV_BOUNDARY_MODULE_NAME
    value: egov-location
  - name: EGOV_BOUNDARY_HIERARCHY_CODE
    value: ADMIN
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    value: ADMIN
  - name: EGOV_KUBE_CONFIG
    value: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNdmFrTkRRV1ZoWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkplazFFVFhoT1JFRTFUVlJCZUU5R2IxaEVWRTE2VFVSTmVFMVVRVFZOVkVGNFQwWnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVFZCWUNtZHRNbGhvTmxGa1ZVTlpPR1p3TWt0WlUyWnNPVXhrWkZWS2QzaEdTVVJzTjI1TVFVNTJjMDlDYzNwdFVXVlhLMUFyV2l0UFFXeHBWM3BWYVRGbFZYWUtWMGhNWWtaWFdGTkZSR04yWmxwTWNqaGhkV2sxUjFWNWJrOXFNaThyWW1jMVUyNTVRMGg2TTBkc01tVk9OQ3R0ZFU1YVEyZEdZMWhyVFVsQlNFcHVlUXBtZFhsd1UxTjFSMlJUVTFGMU0wcHNZMjVQVDFjd1lsbFFNbUpKUzBzd09VVjRZMEptWVdaTFdXRm9ZWFZhY1dWb1UyWk5OVzg1WVVNeWVERkNRbE4wQ2s0NFdGUnBaVGw2UlVkM1pUUklkSEZvVUhCalZFUlNVVWwyYlVKSlNuTXJkMDFZZEhkVGEybHZibTUyU1RRdll6RlZPRUp0TmxORGNWZzJTWGRxTlhBS01HczFVWEJ0U1VWc1kxRlJVRE00TWxWUGVsZElXU3RIWjB3d2NGbGtWMjlSTjBKUlZrTmpPSEZXUjNKak9FdzNXa2RLWjBWSWIyeDBMM05oUlRsb2JncFJURUZtWVZBMVlVSjBSMXBrZDNrNFFteEZRMEYzUlVGQllVNWFUVVpqZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBoUldVUldVakJQUWtKWlJVWkpMMWRqTURoS1JqZDVNVTVXU0hWNE9YUkdPWEJxTkZZeFRuaE5RbFZIUVRGVlpFVlJVVThLVFVGNVEwTnRkREZaYlZaNVltMVdNRnBZVFhkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJHZG5SVUpCU1VwaWRreGFVVWRwVEdsV01UQkNSMU40YUFwSk4xUm1hbk50ZWs1MlNrSXdVR1V2UzAxSVdWTXZaMVZQYlRRMEx6VjBMMWR5VFdJemREUjFNSFZXVEhocmNuZHVMemxJTkhKMFNHNUNkVWxKYkVsaENubHBRM1JUVEVaaVNITllaVmxLUWtGelJXMVRNMDFtUXpoR2QzZE5kekp5ZUd4aVNIbDBObTF1WmtzME5EVm9NVXN2Y2t0NFQzbDRRM2hDYzNOcVRFa0tObVowY25aWVNra3JXamh1VENzclFsUkJlVFpMUmpOVVQwdzNUMmhtU3pKeGQyUnVXakJYWnpSYWQyaHJiVmhZU0hRelRtNXRaVFo1TldGc1pqQjJTd3B2VEdaWE4yOXBaRE5FZUdSSU5rOVdjekZ0TkRnd2RGQkdWVFo1YURWRmRGcHNLMk5hVWxwVU5GUk5iVnBZU0RocU5XdElSV05ZUTNaNGJHTkhPRTVCQ2xSc1VHVnlaREZTU1dWM05GYzJhRzE2VVc1TGRTOVFWM050WVV3eWJrRkNkVkJsYTFkTU5UazJaRkJzY2t0VFYydE1kblFyWWxGMmVucE1LMnhEYzNVS1pVaHZQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CiAgICBzZXJ2ZXI6IGh0dHBzOi8vQzBFM0U1QzJBNDIyNURGNEU3NzUzQjg0QUIxQTYzN0MuZ3I3LmFwLXNvdXRoLTEuZWtzLmFtYXpvbmF3cy5jb20KICBuYW1lOiBhcm46YXdzOmVrczphcC1zb3V0aC0xOjY4MDE0ODI2NzA5MzpjbHVzdGVyL21vei1oZWFsdGgtZGV2CmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBhcm46YXdzOmVrczphcC1zb3V0aC0xOjY4MDE0ODI2NzA5MzpjbHVzdGVyL21vei1oZWFsdGgtZGV2CiAgICB1c2VyOiBhcm46YXdzOmVrczphcC1zb3V0aC0xOjY4MDE0ODI2NzA5MzpjbHVzdGVyL21vei1oZWFsdGgtZGV2CiAgbmFtZTogYXJuOmF3czpla3M6YXAtc291dGgtMTo2ODAxNDgyNjcwOTM6Y2x1c3Rlci9tb3otaGVhbHRoLWRldgpjdXJyZW50LWNvbnRleHQ6IGFybjphd3M6ZWtzOmFwLXNvdXRoLTE6NjgwMTQ4MjY3MDkzOmNsdXN0ZXIvbW96LWhlYWx0aC1kZXYKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBhcm46YXdzOmVrczphcC1zb3V0aC0xOjY4MDE0ODI2NzA5MzpjbHVzdGVyL21vei1oZWFsdGgtZGV2CiAgdXNlcjoKICAgIGV4ZWM6CiAgICAgIGFwaVZlcnNpb246IGNsaWVudC5hdXRoZW50aWNhdGlvbi5rOHMuaW8vdjFiZXRhMQogICAgICBhcmdzOgogICAgICAtIC0tcmVnaW9uCiAgICAgIC0gYXAtc291dGgtMQogICAgICAtIGVrcwogICAgICAtIGdldC10b2tlbgogICAgICAtIC0tY2x1c3Rlci1uYW1lCiAgICAgIC0gbW96LWhlYWx0aC1kZXYKICAgICAgY29tbWFuZDogYXdzCiAgICAgIGVudjoKICAgICAgLSBuYW1lOiBBV1NfUFJPRklMRQogICAgICAgIHZhbHVlOiBkZWZhdWx0CiAgICAgIGludGVyYWN0aXZlTW9kZTogSWZBdmFpbGFibGUKICAgICAgcHJvdmlkZUNsdXN0ZXJJbmZvOiBmYWxzZQ==
  - name: EGOV_KUBE_NAMESPACE
    value: egov
  - name: EGOV_KUBE_MDMS_POD
    value: egov-mdms-service
  - name: EGOV_KUBE_IS_CLUSTER
    value: "true"
  - name: EGOV_KUBE_CLUSTER_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: aws-cluster-name
  - name: EGOV_AWS_REGION
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: aws-region
  - name: EGOV_AWS_CREDENTIALS_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: aws-key
  - name: EGOV_AWS_CREDENTIALS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: aws-secret-key
  - name: EGOV_CLUSTER_ENDPOINT_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: aws-cluster-ip
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  