
{{- with index .Values "cluster-configs" "secrets" "hcm-moz-impl" }}
{{- if index . "kubeconfig" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  kubeconfig: {{ index . "kubeconfig" | b64enc | quote }}
  githubusername: {{ index . "githubusername"  | b64enc | quote }}
  githubpat: {{ index . "githubpat"  | b64enc | quote }}
{{- end }}
{{- end }}